name: ci

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        os:
          - windows-latest
          - ubuntu-latest
          - macos-13
          - macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check Node.js installation
        run: |
          node --version
          npm --version
      - name: Install dependencies
        run: |
          npm install
      - name: npm test
        run: |
          npm test --verbose
